import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['deep-diff.ts'],
	tsconfig: 'tsconfig.lib.json',
	bundle: true,
	platform: 'browser',
	format: 'cjs',
	target: 'es6',
	external: [],
	logLevel: 'info',
	watch: false,
	sourcemap: 'external',
	minify: true,
	treeShaking: false,
	outfile: 'dist-diff/umd/deep-diff.min.js',
}).catch(() => process.exit(1));
