name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 23.x]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - name: package-install
        run: npm install
      - name: unit-test
        run: npm run test
      - name: dist-build
        run: npm run build
