name: publish-diff
on:
  workflow_dispatch:
    inputs:
      publish:
        description: Enable Publish
        required: true
        type: boolean
env:
  VERSION: ${{ github.ref }}
jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/diff-lib
    permissions:
      contents: read
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.VERSION }}
      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org
      - name: clean-build
        run: npm ci && npm run buildlib
      - name: npm-publish
        run: echo 'no'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
